"""airquality table

Revision ID: 90b425455442
Revises: 4cce62ea3e4f
Create Date: 2022-09-13 16:02:55.718537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90b425455442'
down_revision = '4cce62ea3e4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_air_quality_timestamp'), 'air_quality', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_air_quality_timestamp'), table_name='air_quality')
    # ### end Alembic commands ###
