"""message

Revision ID: c0084f33d207
Revises: e980deecadde
Create Date: 2022-10-15 11:57:02.775705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0084f33d207'
down_revision = 'e980deecadde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('temperature_lower_bound', sa.Integer(), nullable=True),
    sa.Column('temperature_upper_bound', sa.Integer(), nullable=True),
    sa.Column('humidity_lower_bound', sa.Integer(), nullable=True),
    sa.Column('humidity_upper_bound', sa.Integer(), nullable=True),
    sa.Column('co2_lower_bound', sa.Integer(), nullable=True),
    sa.Column('co2_upper_bound', sa.Integer(), nullable=True),
    sa.Column('particles_lower_bound', sa.Integer(), nullable=True),
    sa.Column('particles_upper_bound', sa.Integer(), nullable=True),
    sa.Column('tvoc_lower_bound', sa.Integer(), nullable=True),
    sa.Column('tvoc_upper_bound', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings')
    # ### end Alembic commands ###
