"""message

Revision ID: e980deecadde
Revises: f880f3d1f913
Create Date: 2022-10-10 12:59:47.098621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e980deecadde'
down_revision = 'f880f3d1f913'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('air_quality', sa.Column('js_timestamp', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('air_quality', 'js_timestamp')
    # ### end Alembic commands ###
